Created the FAQ and Donate Page
stevensblueprint/inreach-website pull request #97
Opened 2024-12-11 01:45 UTC by Lucasha11

Created both the FAQ and Donate pages

2024-12-11 03:16 UTC, ShawnAviles commented
@Lucasha11 pls put photo of the pages that were added - would make reviewing PR a lot easier so we know what we are looking for

2024-12-11 03:18 UTC, ShawnAviles commented
There is only a jpg file added in this PR... no markdown so I assume it's not done or you may have not committed the pages yet

2024-12-11 18:05 UTC, Lucasha11 commented
FAQ Page:
<img width="1440" alt="Screenshot 2024-12-11 at 1 03 08 PM" src="https://github.com/user-attachments/assets/4ab2928c-a876-4a17-be1e-166be1710296" />
<img width="1440" alt="Screenshot 2024-12-11 at 1 03 30 PM" src="https://github.com/user-attachments/assets/3baab9b3-3424-4350-a5e0-21a4ed9907a5" />
<img width="1440" alt="Screenshot 2024-12-11 at 1 03 44 PM" src="https://github.com/user-attachments/assets/a716c72a-1357-4623-be2a-4bae404a1113" />
<img width="1440" alt="Screenshot 2024-12-11 at 1 03 57 PM" src="https://github.com/user-attachments/assets/756c892a-c39d-4a23-8a48-323fdcd6662c" />

Donate Page: 
<img width="1440" alt="Screenshot 2024-12-11 at 1 05 23 PM" src="https://github.com/user-attachments/assets/5b98840e-db26-48f2-92cc-ac705949415e" />
<img width="1440" alt="Screenshot 2024-12-11 at 1 05 31 PM" src="https://github.com/user-attachments/assets/3d49146a-7f66-4dd4-81d7-9c1c312328e1" />

2024-12-18 03:41 UTC, Lucasha11 commented
[Donate page](http://localhost:3000/donate)
[FAQs Page](http://localhost:3000/FAQs)

2024-12-18 04:37 UTC, ShawnAviles requested changes
There were a lot of changes made to components in the PR, was that intentional? or is that some issue from not pulling from main and other commits got added to this? @miguel-merlin @Lucasha11

2024-12-18 04:37 UTC, ShawnAviles commented on public/FAQ/FAQs cover.jpg
Should there be duplicates of these images saved?

2024-12-18 04:37 UTC, ShawnAviles commented on content/pages/Donate.mdx
> +  - richTextLeft: "<YoutubeEmbed url=\"https://www.youtube.com/watch?reload=9&v=l_sm8Q1r3d8\" />\n\nYour donation matters! Here’s the impact you can make:\n\n\U0001F49A $25 = 21 more people supported
I believe the youtube video id is incorrect. doesn't play anything

<img width="1482" alt="Screenshot 2024-12-17 at 11 33 56 PM" src="https://github.com/user-attachments/assets/622fd59c-db3f-4ae9-b08f-c8057312be98" />

2024-12-18 04:38 UTC, ShawnAviles commented
Also the routes are all caps, everywhere else they are all lowercase.

i.e. `/Donate` should be `/donate` and `/FAQs` should be `/faqs` for consistency

2024-12-18 18:25 UTC, j-ferber approved these changes
LGTM

2024-12-18 18:29 UTC, ShawnAviles approved these changes

2024-12-18 18:31 UTC, merged